export function createInitialGameState() {
  return {
    character: null,
    scenario: null,
    seed: null,
    rng: null,
    state: null,
    turn: 1,
    turnLog: [],
    highestPosIdx: 0,
    allFlags: [],
    signals: null,
    consecutiveWater0: 0,
    consecutiveCollapses: 0,
    runNumber: 0,
    whiteWindRisk: 0,
    day: 1,
    minutesOfDay: 360,
    irreversibleTriggered: false,
    irreversibleTurn: null,
    acclimatization: 0,
    consecutiveAdvances: 0,
    tutorialSeen: {},
    journalReturnScreen: 'debrief',
    persistenceTurns: 0,
    pressureHistory: [],
    runLogRecords: [],
    modelReady: false,
    hasSummited: false,
    finalOutcome: 'Strategic Retreat',
    permitDay: 1,
    permitMaxDays: 20,
    photoShotsTaken: 0,
    photoInsightTurns: 0,
    lastPhotoTurn: -99,
    photoLastEffectLabel: '',
    turnDecisionStartedAt: 0,
    decisionTimeSpentMs: 0,
    decisionWindowExceeded: false,
    decisionWindowEffect: null,
    decisionWindowProfile: null,
    decisionPauseUsed: false,
    decisionPauseTurnsLeft: 0,
    lateSignalDeterminantTurns: 0,
    lateSignalEvents: [],
    onboardingLayer: 'essentials',
    currentPrimaryAlert: { label: 'stable', level: 'stable', type: 'stable' },
  };
}

export const G = createInitialGameState();
